-- oracle query: performance-p99-llm-latency
-- source tile: P99 Llm Latency (page: Latency)
-- pinned block: fe6423cc9775b6dc61f7f7047dd4424603ddb3a1
-- dashboard date default: 7 days
-- call_row_policy: raw_row
-- GENERATED by oracle/gen_oracle.py — independent LookML
-- translation; must never share the production union SQL.
SELECT
  PERCENTILE_CONT(total_ms, 0.50) OVER () AS p50_llm_latency,
  PERCENTILE_CONT(total_ms, 0.75) OVER () AS p75_llm_latency,
  PERCENTILE_CONT(total_ms, 0.90) OVER () AS p90_llm_latency,
  PERCENTILE_CONT(total_ms, 0.99) OVER () AS p99_llm_latency
FROM (
  SELECT * FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_llm_response`
  WHERE timestamp >= TIMESTAMP(@start_date, 'UTC')
    AND timestamp < TIMESTAMP(DATE_ADD(@end_date, INTERVAL 1 DAY), 'UTC')
    AND (ARRAY_LENGTH(@filter_agent) = 0 OR agent IN UNNEST(@filter_agent))
    AND (ARRAY_LENGTH(@filter_span_id) = 0 OR span_id IN UNNEST(@filter_span_id))
    AND (ARRAY_LENGTH(@filter_trace_id) = 0 OR trace_id IN UNNEST(@filter_trace_id))
    AND (ARRAY_LENGTH(@filter_user_id) = 0 OR user_id IN UNNEST(@filter_user_id))
)
QUALIFY ROW_NUMBER() OVER () = 1
ORDER BY p50_llm_latency DESC, p75_llm_latency DESC, p90_llm_latency DESC, p99_llm_latency DESC
LIMIT 500
