-- oracle query: performance-p99-tool-latency
-- source tile: P99 Tool Latency (page: Latency)
-- pinned block: fe6423cc9775b6dc61f7f7047dd4424603ddb3a1
-- dashboard date default: 7 days
-- call_row_policy: raw_row
-- GENERATED by oracle/gen_oracle.py — independent LookML
-- translation; must never share the production union SQL.
SELECT
  PERCENTILE_CONT(total_ms, 0.50) OVER () AS p50_tool_latency,
  PERCENTILE_CONT(total_ms, 0.75) OVER () AS p75_tool_latency,
  PERCENTILE_CONT(total_ms, 0.90) OVER () AS p90_tool_latency,
  PERCENTILE_CONT(total_ms, 0.99) OVER () AS p99_tool_latency
FROM (
  SELECT * FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_tool_completed`
  WHERE timestamp >= TIMESTAMP(@start_date, 'UTC')
    AND timestamp < TIMESTAMP(DATE_ADD(@end_date, INTERVAL 1 DAY), 'UTC')
)
QUALIFY ROW_NUMBER() OVER () = 1
LIMIT 500
