-- oracle query: performance-average-tool-latency-ms
-- source tile: Average Tool Latency (ms) (page: Latency)
-- pinned block: fe6423cc9775b6dc61f7f7047dd4424603ddb3a1
-- dashboard date default: 7 days
-- call_row_policy: raw_row
-- GENERATED by oracle/gen_oracle.py — independent LookML
-- translation; must never share the production union SQL.
SELECT
  AVG(total_ms) AS average_tool_latency
FROM (
  SELECT * FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_tool_completed`
  WHERE timestamp >= TIMESTAMP(@start_date, 'UTC')
    AND timestamp < TIMESTAMP(DATE_ADD(@end_date, INTERVAL 1 DAY), 'UTC')
    AND (ARRAY_LENGTH(@filter_agent) = 0 OR agent IN UNNEST(@filter_agent))
    AND (ARRAY_LENGTH(@filter_span_id) = 0 OR span_id IN UNNEST(@filter_span_id))
    AND (ARRAY_LENGTH(@filter_tool_name) = 0 OR tool_name IN UNNEST(@filter_tool_name))
    AND (ARRAY_LENGTH(@filter_trace_id) = 0 OR trace_id IN UNNEST(@filter_trace_id))
    AND (ARRAY_LENGTH(@filter_user_id) = 0 OR user_id IN UNNEST(@filter_user_id))
)
ORDER BY average_tool_latency DESC
LIMIT 500
