-- oracle query: usage-tool-invocations
-- source tile: Tool Invocations (page: Tool Usage)
-- pinned block: fe6423cc9775b6dc61f7f7047dd4424603ddb3a1
-- dashboard date default: 14 days
-- call_row_policy: raw_row
-- GENERATED by oracle/gen_oracle.py — independent LookML
-- translation; must never share the production union SQL.
SELECT
  tool_name AS tool_name,
  COUNT(DISTINCT invocation_id) AS total_invocations
FROM (
  SELECT * FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_tool_completed`
  WHERE timestamp >= TIMESTAMP(@start_date, 'UTC')
    AND timestamp < TIMESTAMP(DATE_ADD(@end_date, INTERVAL 1 DAY), 'UTC')
    AND tool_name IS NOT NULL
    AND (ARRAY_LENGTH(@filter_agent) = 0 OR agent IN UNNEST(@filter_agent))
    AND (ARRAY_LENGTH(@filter_span_id) = 0 OR span_id IN UNNEST(@filter_span_id))
    AND (ARRAY_LENGTH(@filter_trace_id) = 0 OR trace_id IN UNNEST(@filter_trace_id))
    AND (ARRAY_LENGTH(@filter_user_id) = 0 OR user_id IN UNNEST(@filter_user_id))
)
GROUP BY tool_name
ORDER BY total_invocations DESC, tool_name
LIMIT 10
