-- oracle query: usage-total-tokens-consumption-over-the-time
-- source tile: Total Tokens Consumption Over the Time (page: Token Consumption)
-- pinned block: fe6423cc9775b6dc61f7f7047dd4424603ddb3a1
-- dashboard date default: 14 days
-- call_row_policy: raw_row
-- GENERATED by oracle/gen_oracle.py — independent LookML
-- translation; must never share the production union SQL.
SELECT
  DATE(timestamp, 'UTC') AS timestamp_date,
  SUM(COALESCE(SAFE_CAST(JSON_VALUE(usage_metadata, '$.total_token_count') AS INT64), SAFE_CAST(JSON_VALUE(usage_metadata, '$.total_tokens') AS INT64), usage_total_tokens)) AS total_tokens_consumed
FROM (
  SELECT * FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_llm_response`
  WHERE timestamp >= TIMESTAMP(@start_date, 'UTC')
    AND timestamp < TIMESTAMP(DATE_ADD(@end_date, INTERVAL 1 DAY), 'UTC')
    AND (ARRAY_LENGTH(@filter_agent) = 0 OR agent IN UNNEST(@filter_agent))
    AND (ARRAY_LENGTH(@filter_span_id) = 0 OR span_id IN UNNEST(@filter_span_id))
    AND (ARRAY_LENGTH(@filter_trace_id) = 0 OR trace_id IN UNNEST(@filter_trace_id))
    AND (ARRAY_LENGTH(@filter_user_id) = 0 OR user_id IN UNNEST(@filter_user_id))
)
GROUP BY timestamp_date
ORDER BY timestamp_date DESC
LIMIT 500
