-- oracle query: usage-top-5-agents-split-by-session-count
-- source tile: Top 5 Agents Split by Session Count (page: Agent & Sessions)
-- pinned block: fe6423cc9775b6dc61f7f7047dd4424603ddb3a1
-- dashboard date default: 14 days
-- call_row_policy: raw_row
-- GENERATED by oracle/gen_oracle.py — independent LookML
-- translation; must never share the production union SQL.
SELECT
  agent AS agent,
  COUNT(DISTINCT session_id) AS total_sessions
FROM (
  WITH all_events AS (
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_user_message_received`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_llm_request`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_llm_response`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_llm_error`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_tool_starting`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_tool_completed`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_tool_error`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_agent_starting`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_agent_completed`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_invocation_starting`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_invocation_completed`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_state_delta`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_hitl_credential_request`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_hitl_confirmation_request`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_hitl_input_request`
  )
  SELECT * FROM all_events
  WHERE timestamp >= TIMESTAMP(@start_date, 'UTC')
    AND timestamp < TIMESTAMP(DATE_ADD(@end_date, INTERVAL 1 DAY), 'UTC')
    AND (ARRAY_LENGTH(@filter_agent) = 0 OR agent IN UNNEST(@filter_agent))
    AND (ARRAY_LENGTH(@filter_span_id) = 0 OR span_id IN UNNEST(@filter_span_id))
    AND (ARRAY_LENGTH(@filter_trace_id) = 0 OR trace_id IN UNNEST(@filter_trace_id))
    AND (ARRAY_LENGTH(@filter_user_id) = 0 OR user_id IN UNNEST(@filter_user_id))
)
GROUP BY agent
ORDER BY total_sessions DESC, agent
LIMIT 5
