-- oracle query: usage-traces-split-by-agent
-- source tile: Traces split by Agent (page: Agent & Sessions)
-- pinned block: fe6423cc9775b6dc61f7f7047dd4424603ddb3a1
-- dashboard date default: 14 days
-- call_row_policy: raw_row
-- GENERATED by oracle/gen_oracle.py — independent LookML
-- translation; must never share the production union SQL.
WITH base AS (
SELECT
  agent AS agent,
  COUNT(DISTINCT trace_id) AS total_traces
FROM (
  WITH all_events AS (
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_user_message_received`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_llm_request`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_llm_response`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_llm_error`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_tool_starting`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_tool_completed`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_tool_error`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_agent_starting`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_agent_completed`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_invocation_starting`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_invocation_completed`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_state_delta`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_hitl_credential_request`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_hitl_confirmation_request`
    UNION ALL
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_hitl_input_request`
  )
  SELECT * FROM all_events
  WHERE timestamp >= TIMESTAMP(@start_date, 'UTC')
    AND timestamp < TIMESTAMP(DATE_ADD(@end_date, INTERVAL 1 DAY), 'UTC')
    AND (ARRAY_LENGTH(@filter_agent) = 0 OR agent IN UNNEST(@filter_agent))
    AND (ARRAY_LENGTH(@filter_span_id) = 0 OR span_id IN UNNEST(@filter_span_id))
    AND (ARRAY_LENGTH(@filter_trace_id) = 0 OR trace_id IN UNNEST(@filter_trace_id))
)
GROUP BY agent
),
aux AS (
SELECT agent AS agent, SUM(COALESCE(SAFE_CAST(JSON_VALUE(usage_metadata, '$.total_token_count') AS INT64), SAFE_CAST(JSON_VALUE(usage_metadata, '$.total_tokens') AS INT64), usage_total_tokens)) AS filter_value FROM (
  SELECT * FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_llm_response`
  WHERE timestamp >= TIMESTAMP(@start_date, 'UTC')
    AND timestamp < TIMESTAMP(DATE_ADD(@end_date, INTERVAL 1 DAY), 'UTC')
    AND (ARRAY_LENGTH(@filter_agent) = 0 OR agent IN UNNEST(@filter_agent))
    AND (ARRAY_LENGTH(@filter_span_id) = 0 OR span_id IN UNNEST(@filter_span_id))
    AND (ARRAY_LENGTH(@filter_trace_id) = 0 OR trace_id IN UNNEST(@filter_trace_id))
)
GROUP BY agent
)
SELECT base.*
FROM base
JOIN aux ON base.agent = aux.agent
WHERE aux.filter_value IS NOT NULL
ORDER BY total_traces DESC, agent
LIMIT 5
