-- oracle query: usage-top-5-agents-by-llm-calls
-- source tile: Top 5 Agents by LLM Calls (page: LLM Interactions)
-- pinned block: fe6423cc9775b6dc61f7f7047dd4424603ddb3a1
-- dashboard date default: 14 days
-- call_row_policy: raw_row
-- GENERATED by oracle/gen_oracle.py — independent LookML
-- translation; must never share the production union SQL.
SELECT
  agent AS agent,
  COUNT(DISTINCT CONCAT(trace_id, '|', span_id)) AS total_llm_calls
FROM (
  SELECT * FROM `{{PROJECT}}.{{DATASET}}.{{VIEW_PREFIX}}_llm_response`
  WHERE timestamp >= TIMESTAMP(@start_date, 'UTC')
    AND timestamp < TIMESTAMP(DATE_ADD(@end_date, INTERVAL 1 DAY), 'UTC')
)
GROUP BY agent
ORDER BY total_llm_calls DESC
LIMIT 500
