#!/usr/bin/env python3
"""Render sql/*.sql.tmpl with the sentinel bindings.

Deterministic: same inputs must produce byte-identical output (CI asserts no
drift between the committed generated files and a fresh render).

Checks enforced:
  * every {{PLACEHOLDER}} in the template has a binding;
  * no placeholder survives rendering;
  * every sentinel value is unique and appears only where a placeholder was
    (count of occurrences == count of placeholder occurrences), so the
    Linking API string replacement can never corrupt unrelated identifiers.
"""

import re
import sys
import yaml

PAIRS = [
    ("sql/events_v1.sql.tmpl", "sql/events_v1.template.sql"),
    ("sql/preflight.sql.tmpl", "sql/preflight.template.sql"),
]
PLACEHOLDER_RE = re.compile(r"\{\{([A-Z_]+)\}\}")


def main() -> int:
    bindings = yaml.safe_load(open("bindings/template_bindings.yaml"))
    values = bindings["placeholders"]

    if len(set(values.values())) != len(values):
        print("ERROR: sentinel values must be unique", file=sys.stderr)
        return 1

    for src, dst in PAIRS:
        tmpl = open(src).read()
        names = set(PLACEHOLDER_RE.findall(tmpl))
        missing = names - set(values)
        if missing:
            print(f"ERROR: {src}: unbound placeholders {sorted(missing)}",
                  file=sys.stderr)
            return 1
        counts = {n: len(re.findall(r"\{\{" + n + r"\}\}", tmpl))
                  for n in names}
        out = tmpl
        for name in names:
            out = out.replace("{{" + name + "}}", values[name])
        if PLACEHOLDER_RE.search(out):
            print(f"ERROR: {src}: unresolved placeholder after render",
                  file=sys.stderr)
            return 1
        for name in names:
            if out.count(values[name]) != counts[name]:
                print(f"ERROR: {src}: sentinel {values[name]!r} collides "
                      "with other text", file=sys.stderr)
                return 1
        with open(dst, "w") as fh:
            fh.write("-- GENERATED by tools/render_template.py from "
                     f"{src} — do not hand-edit.\n")
            fh.write(out)
        print(f"rendered {dst}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
