#!/usr/bin/env python3
"""Render the public configurator's immutable report bindings."""

import json
import pathlib

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent


def load_mapping(path: pathlib.Path) -> dict:
    value = yaml.safe_load(path.read_text())
    if not isinstance(value, dict):
        raise ValueError(f"{path}: expected a mapping")
    return value


def main() -> int:
    report = load_mapping(ROOT / "bindings/report_template.yaml")
    bindings = load_mapping(ROOT / "bindings/template_bindings.yaml")
    placeholders = bindings.get("placeholders")
    if not isinstance(placeholders, dict):
        raise ValueError("template_bindings.yaml: placeholders must be a mapping")

    config = {
        "reportId": report["report_id"],
        "dataSourceAlias": report["data_source_alias"],
        "sentinels": {
            "project": placeholders["PROJECT"],
            "dataset": placeholders["DATASET"],
            "viewPrefix": placeholders["VIEW_PREFIX"],
        },
        "defaultViewPrefix": "v",
        "defaultTable": "agent_events",
    }
    rendered = (
        "// Generated by tools/render_web_config.py; do not edit.\n"
        f"export const REPORT_CONFIG = Object.freeze({json.dumps(config, indent=2)});\n"
    )
    (ROOT / "docs/report-config.mjs").write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
