-- GENERATED by tools/render_template.py from sql/preflight.sql.tmpl — do not hand-edit.
-- preflight.sql.tmpl — structural compatibility check, run by the hydration
-- helper as the current user BEFORE emitting a Linking API URL.
--
-- Reports every missing required view and every missing required source
-- column BY NAME (one row per problem; zero rows = preflight passes).
-- Structural pass means "preflight-compatible" only — never parity-certified
-- (see the certification lifecycle in the governing contract, issue #365).
WITH required_views AS (
  SELECT view_suffix, required_column, column_type FROM UNNEST([
    -- Common columns are checked on every one of the 15 v1 views.
    STRUCT('_ALL_' AS view_suffix, 'timestamp' AS required_column, 'TIMESTAMP' AS column_type),
    ('_ALL_', 'event_type', 'STRING'),
    ('_ALL_', 'agent', 'STRING'),
    ('_ALL_', 'session_id', 'STRING'),
    ('_ALL_', 'invocation_id', 'STRING'),
    ('_ALL_', 'user_id', 'STRING'),
    ('_ALL_', 'trace_id', 'STRING'),
    ('_ALL_', 'span_id', 'STRING'),
    ('_ALL_', 'parent_span_id', 'STRING'),
    ('_ALL_', 'status', 'STRING'),
    ('_ALL_', 'error_message', 'STRING'),
    ('_ALL_', 'is_truncated', 'BOOL'),
    -- Required source columns for the token-precedence rule and metrics.
    ('llm_response', 'usage_metadata', 'JSON'),
    ('llm_response', 'usage_prompt_tokens', 'INT64'),
    ('llm_response', 'usage_completion_tokens', 'INT64'),
    ('llm_response', 'usage_total_tokens', 'INT64'),
    ('llm_response', 'total_ms', 'INT64'),
    ('llm_response', 'ttft_ms', 'INT64'),
    ('llm_response', 'model_version', 'STRING'),
    ('tool_completed', 'tool_name', 'STRING'),
    ('tool_completed', 'tool_origin', 'STRING'),
    ('tool_completed', 'total_ms', 'INT64'),
    ('tool_error', 'tool_name', 'STRING'),
    ('tool_error', 'tool_origin', 'STRING'),
    ('tool_error', 'total_ms', 'INT64')
  ])
),
v1_views AS (
  SELECT suffix FROM UNNEST([
    'user_message_received', 'llm_request', 'llm_response', 'llm_error',
    'tool_starting', 'tool_completed', 'tool_error', 'agent_starting',
    'agent_completed', 'invocation_starting', 'invocation_completed',
    'state_delta', 'hitl_credential_request', 'hitl_confirmation_request',
    'hitl_input_request'
  ]) AS suffix
),
expected AS (
  SELECT
    CONCAT('vsentinelbqaa_', v.suffix) AS view_name,
    r.required_column,
    r.column_type
  FROM v1_views v
  JOIN required_views r
    ON r.view_suffix = '_ALL_' OR r.view_suffix = v.suffix
),
actual AS (
  SELECT table_name, column_name, data_type
  FROM `test-project-0728-467323.bqaa_fixture_adk_1_27_0`.INFORMATION_SCHEMA.COLUMNS
),
-- Object-type check: a base table shadowing a generated-view name must be
-- rejected (WRONG_OBJECT_TYPE), not silently accepted via COLUMNS alone.
objects AS (
  SELECT table_name, table_type
  FROM `test-project-0728-467323.bqaa_fixture_adk_1_27_0`.INFORMATION_SCHEMA.TABLES
)
SELECT
  e.view_name,
  e.required_column,
  e.column_type AS expected_type,
  a.data_type AS observed_type,
  o.table_type AS observed_object_type,
  CASE
    WHEN o.table_name IS NULL THEN 'MISSING_VIEW'
    WHEN o.table_type != 'VIEW' THEN 'WRONG_OBJECT_TYPE'
    WHEN a.column_name IS NULL THEN 'MISSING_COLUMN'
    ELSE 'TYPE_MISMATCH'
  END AS problem
FROM expected e
LEFT JOIN objects o
  ON o.table_name = e.view_name
LEFT JOIN actual a
  ON a.table_name = e.view_name AND a.column_name = e.required_column
WHERE o.table_name IS NULL
   OR o.table_type != 'VIEW'
   OR a.column_name IS NULL
   OR a.data_type != e.column_type
ORDER BY e.view_name, e.required_column
